<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	
	<title>Orbas - Login</title>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="/css/bootstrap/bootstrap.min.css">
	<!-- Bootstrap responsive -->
	<link rel="stylesheet" href="/css/bootstrap/bootstrap-responsive.min.css">
	<!-- icheck -->
	<link rel="stylesheet" href="/css/plugins/icheck/all.css">
	<!-- Theme CSS -->
	<link rel="stylesheet" href="/css/style.css">
	<!-- Color CSS -->
	<link rel="stylesheet" href="/css/themes.css">
	
	<link rel="stylesheet" href="/js/plugins/toastr/toastr.css" />

	<!-- jQuery -->
	<script src="/js/jquery.min.js"></script>
	
	<!-- Nice Scroll -->
	<script src="/js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
	<!-- Validation -->
	<script src="/js/plugins/validation/jquery.validate.min.js"></script>
	<script src="/js/plugins/validation/additional-methods.min.js"></script>
	<!-- icheck -->
	<script src="/js/plugins/icheck/jquery.icheck.min.js"></script>
	<!-- Bootstrap -->
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/eakroko.js"></script>
	
	<script type="text/javascript" src="/js/plugins/toastr/toastr.min.js"></script>
	<script type="text/javascript" src="/js/orbas.js"></script>
	
	<script type="text/javascript">
	   $(function(){
		   <? if($this->message) { ?>
		   Orbas.message('<?= $this->message['type']?>', '<?= nl2br($this->escape(addslashes($this->message['message']))) ?>');
		   <? } ?>
	   });
	</script>

	<!--[if lte IE 9]>
		<script src="/js/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
	<![endif]-->
	

	<!-- Favicon -->
	<link rel="shortcut icon" href="img/favicon.ico" />
	<!-- Apple devices Homescreen icon -->
	<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png" />

	<script type="text/javascript">
	   $(function(){
		   $("#EMAIL").focus();
	   });
	</script>
	
</head>

<body class='login'>
	<div class="wrapper">
	   
		<div class="login-body">
			<h2><img src="/img/custom/logo.png" /></h2>
			<form action="<?= $this->simpleUrl('login.do') ?>" method="post" class="form-validate">
				<div class="control-group">
					<div class="email controls">
						<input type="email" id="EMAIL" name="EMAIL" value="<?= @$this->data['EMAIL'] ?>" placeholder="Email address" class="input-block-level" data-rule-required="true" data-rule-email="true" />
					</div>
				</div>
				<div class="control-group">
					<div class="pw controls">
					    <input type="password" name="PASSWORD" placeholder="Password" class="input-block-level" data-rule-required="true" />
					</div>
				</div>
				<div class="submit">
					<div class="remember">
						<input type="checkbox" name="remember" class='icheck-me' data-skin="square" data-color="blue" id="remember" value="1"> <label for="remember">Remember me</label>
					</div>
					<input type="submit" value="Login" class='btn btn-primary' />
				</div>
			</form>
			<div class="forget">
				<a href="#"><span>Forgot password?</span></a>
			</div>
		</div>
	</div>
</body>

</html>
