
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	
	<title>FLAT - Error page</title>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="/css/bootstrap/bootstrap.min.css">
	<!-- Bootstrap responsive -->
	<link rel="stylesheet" href="/css/bootstrap/bootstrap-responsive.min.css">
	<!-- Theme CSS -->
	<link rel="stylesheet" href="/css/style.css">
	<!-- Color CSS -->
	<link rel="stylesheet" href="/css/themes.css">


	<!-- jQuery -->
	<script src="/js/jquery.min.js"></script>
	
	<!-- Nice Scroll -->
	<script src="/js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
	<!-- Bootstrap -->
	<script src="/js/bootstrap.min.js"></script>

	<!--[if lte IE 9]>
		<script src="/js/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
	<![endif]-->
	

	<!-- Favicon -->
	<link rel="shortcut icon" href="/img/favicon.ico" />
	<!-- Apple devices Homescreen icon -->
	<link rel="apple-touch-icon-precomposed" href="/img/apple-touch-icon-precomposed.png" />

</head>

<body class="error">
	<div class="wrapper">
		<div class="code"><span><?= $this->response->getHttpResponseCode()?></span><i class="icon-warning-sign"></i></div>
		<div class="desc"><?= $this->message ?></div>
		<div class="buttons">
			<div class="pull-left"><a href="javascript:window.history.back()" class="btn"><i class="icon-arrow-left"></i> Back</a></div>
		</div>
	</div>
	
	<? if (isset($this->exception)) { ?>
	<div style="position: absolute; top:55%; left:25%; width:1000px">
		<h3 align="center">Exception information:</h3>
		<p align="center">
			<b>Message:</b> <?php echo $this->exception->getMessage() ?>
		</p>
		<h3>Stack trace:</h3>
		<pre><?php echo $this->exception->getTraceAsString() ?></pre>
		<h3>Request Parameters:</h3>
		<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
    </div>
    <? } ?>
</body>

</html>
